pipeline:
  build:
    image: plugins/docker
    commands: [ make build ]
  
  publish:
    image: plugins/docker
    repo: kyleterry/solarwind
    tag: [ latest ]
    when:
      branch: master
      event: push
