pipeline:
  build:
    image: plugins/docker
    commands: [ make build ]
    custom_dns: [ 1.1.1.1, 8.8.8.8 ]
  
  publish:
    image: plugins/docker
    repo: kyleterry/solarwind
    tag: [ latest ]
    when:
      branch: master
      event: push
